# Generated by Django 3.2.6 on 2021-08-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_vote_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.SmallIntegerField(blank=True, choices=[(1, '👍'), (-1, '👎')]),
        ),
    ]
