# Generated by Django 3.2.6 on 2021-08-26 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_vote_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieimage',
            old_name='Movie',
            new_name='movie',
        ),
    ]
